### ISSUE TITLE
Big renames

### ISSUE THREAD

**Issue by turion** [turion/rhine#45]
# Renames

## renames we would like to have:

* [x] `TimeDomainOf` -> `Time`
* [x] `SyncSF` -> `ClSF`
* [x] `SF` -> `SN` ("signal network")
* [x] `td` -> `time`
* [x] `arrMSync_ :: m a -> SyncSF m cl arbitrary a` to `constMSync`, and then to `constMCl`

## Renames we have to think about once more:

* [x] `Step` ->`FixedStep`?
* [x] `CycleClock` -> `Periodic`?
* [x] `theTag :: SyncSF m cl a (Tag cl)` -> `tagS`?
* [x] `sinceStart` -> `sinceInit`? And:
  * [x] `startClock` -> `initClock`
  * [x] `startSchedule` -> `initSchedule`
* [x] `sinceSimStart` -> ? (#30 )

## Won't rename

* [x] `KeepLast` -> `ZeroOrderHold`
* [x] `ResamplingBuffer.put` -> `ResamplingBuffer.input`
* [x] `ResamplingBuffer.get` -> `ResamplingBuffer.output`

## Aliases to add
* [x] `ResBuf`
* [x] `ParClock`
* [x] `SeqClock`
* [x] `absoluteS = timeInfoOf absolute`, `sinceStartS = timeInfoOf sinceStart`, `sinceTickS = timeInfoOf sinceTick`

# ToDo

## Consistency checks

* [x] Haddock errors
* [x] Skim through code in PR in order to find alignment mistakes

## Changes in other places (immediate)

* [x] Article

## Changes in other places (whenever they update to rhine-0.5)

* sonnendemo
* tutorial

**Comment by turion** [comment]
Yes, that sounds right.

**Comment by turion** [comment]
The step clock (where `Step n` produces ticks `0, n, 2*n` etc. in the integer time domain) should have a better name. @ivanperez-keera any idea how that should be called properly? Something related to "logical clock" or so?

**Comment by turion** [comment]
Should we maybe rename `TimeDomainOf` simply to `TimeDomain`? It would name clash with its assumed type class, which might be confusing, but this could be done with qualified imports.

**Comment by turion** [comment]
There is a type class called `TimeDomain`. I think you can't have a type class and a type (family) of the same name, right?

**Comment by ivanperez-keera** [comment]
When this happens to me, I usually add a suffix to one. You can use F or T for the type function, or C for the class.

Otherwise, and maybe I'm overcomplicating this (or the paper), but, to me, it seems like TimeDomain itself (the class) means something that can easily be expressed in more general (algebraic or category-theoretical) terms. If so, then maybe it would be best to name it something else?

We require that we can measure the difference between them? And what else? What do we assume about that difference?

**Comment by turion** [comment]
When this happens to me, I usually add a suffix to one. You can
        use F or T for the type function, or C for the class.
    
    I'm not sure I like that. I find TimeDomainOf still better than that
    option.
    
      Otherwise, and maybe I'm overcomplicating this (or the paper),
        but, to me, it seems like TimeDomain itself (the class) means
        something that can easily be expressed in more general
        (algebraic or category-theoretical) terms. If so, then maybe it
        would be best to name it something else?
      We require that we can measure the difference between them? And
        what else? What do we assume about that difference?
    
    It definitely can, and there has been a proposal by Alan Jeffrey,
    deriving FRP from those axioms. There are some insights to be
    learned. But it's not too clear to me and I don't want to do the
    research right now. 
    
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/turion/rhine","title":"turion/rhine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/turion/rhine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ivanperez-keera in #45: When this happens to me, I usually add a suffix to one. You can use F or T for the type function, or C for the class.\r\n\r\nOtherwise, and maybe I'm overcomplicating this (or the paper), but, to me, it seems like TimeDomain itself (the class) means something that can easily be expressed in more general (algebraic or category-theoretical) terms. If so, then maybe it would be best to name it something else?\r\n\r\nWe require that we can measure the difference between them? And what else? What do we assume about that difference?"}],"action":{"name":"View Issue","url":"https://github.com/turion/rhine/issues/45#issuecomment-388570548"}}}
      {"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [turion/rhine] Big renames (#45)","sections":[{"text":"","activityTitle":"**Ivan Perez**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@ivanperez-keera","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"turion/rhine\",\"issueId\":45,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"turion/rhine\",\"issueId\":45}"},{"targets":[{"os":"default","uri":"https://github.com/turion/rhine/issues/45#issuecomment-388570548"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":333937469}"}],"themeColor":"26292

**Comment by ivanperez-keera** [comment]
You should check what happened with this answer and that there is no confidential info leaked.

**Comment by ivanperez-keera** [comment]
>> When this happens to me, I usually add a suffix to one. You can use F or T for the type function, or C for the class.
>
> I'm not sure I like that. I find `TimeDomainOf` still better than that option.

Sure. The reason why I opt for the other approach is that you can use it _always_. So, no ad-hoc decisions to be made for each case. I don't think I've seen the use of 'Of' in type functions much, so it's a-typical, but that does not make it wrong. We can always revisit this when we know better.

**Comment by turion** [comment]
The freshly added `CycleClock` should maybe be called `LogicalClock`.

**Comment by ivanperez-keera** [comment]
Logical clocks are more general than a specific type-level step-based clock with a starting point, and they are an established concept in distributed systems.

Unless you are trying to claim that, for some reason, this is *the* way of implementing logical clocks in Rhine, which I would argue against, because I can think of others. And there are kinds/parts of logical clocks that this does not implement.

By the way, is it also possible to say something like `'[1,3,..]` in the type-level list? Because, if it is, the I guess it could be simpler (and also more general?).

**Comment by ivanperez-keera** [comment]
If implemented for general lists, I would call this ListClock. If implemented for a starting point and a delta, I would call these step clocks or fixed-step clocks (these are just my terms, nothing I've read in any literature).

**Comment by turion** [comment]
Right, logical clocks are something different from what I thought. `ListClock` is ok. There is already a `StepClock n`, it's basically `CycleClock '[n]` (see #50 ). Actually, how about calling `CycleClock` `StepsClock`? Then at least the relation between `StepClock` and `StepsClock` is clear.

**Comment by turion** [comment]
I can't get `'[1,3,..]` to work and I suspect that this can't work. Types can't be lazy or infinite.

**Comment by ivanperez-keera** [comment]
> There is already a StepClock n, it's basically CycleClock '[n] (see #50 ).

I thought maybe that could be called `SkipClock` (because it skips steps, keeping one of `n`), or `MacroClock` (because it counts `MacroTicks`, in relation with a faster, global reference clock, which ticks with higher precision and counts `MicroTicks`).

> Actually, how about calling CycleClock StepsClock? Then at least the relation between StepClock and StepsClock is clear.

I'd argue against it. The names are too similar. It will be confusing both in speech and in thinking.

**Comment by ivanperez-keera** [comment]
> I can't get '[1,3,..] to work and I suspect that this can't work. Types can't be lazy or infinite.

Makes sense. Good to know.

**Comment by turion** [comment]
Won't rename `KeepLast` to `ZeroOrderHold` since the latter is usually used restrictively for digital-analog conversion. Instead, I'll add note in the docs/article.

**Comment by turion** [comment]
On second thoughts, names shouldn't be too long. I'll add a note about fixed step length in the docs rather than changing the whole name.

**Comment by ivanperez-keera** [comment]
Which name is too long here?

**Comment by turion** [comment]
`FixedStep`. It's not very long, but still.

**Comment by ivanperez-keera** [comment]
FixedStep is absolutely perfect in length.

In general, and especially at the beginning, opting for longer names is better than opting for short names.

Longer names facilitate understanding, and the worst that can happen is that you'll need a search and replace, and an explanation in the paper/doc.

Shorter names make understanding harder. Search and replace is still possible, it's just generally harder to know what to replace it for because the name is not intuitively descriptive.

**Comment by turion** [comment]
Yes, actually you're right.
